---
# Tasks for configure and run gitlab-ce in docker

- name: Docker {{ gitlab }} | Copy Docker-compose file
  ansible.builtin.template:
    src: templates/docker-compose-ce.j2
    dest: /home/{{ ansible_user }}/docker-compose.yml
    mode: 0755

- name: Docker {{ gitlab }} | Create directory for volumes config
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/gitlab-config
    state: directory

- name: Docker {{ gitlab }} | Create directory for volumes data
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/gitlab-data
    state: directory

- name: Docker {{ gitlab }} | Create and start services
  become: true
  docker_compose:
    project_src: /home/{{ ansible_user }}
  register: output_gitlab

- name: Docker {{ gitlab }} | Show register
  debug: 
    var: output_gitlab