---
# Task for install, configure and run gitlab-ce

- name: Install gitlab | Update apt cache
  become: true
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
  ignore_errors: true

- name: Install gitlab | Install packages
  become: true
  ansible.builtin.apt:
    name: 
      - curl 
      - openssh-server 
      - ca-certificates 
      - tzdata 
      - perl
    state: latest

- name: Install gitlab | Install postfix
  become: true
  ansible.builtin.apt:
    name:
      - postfix
    state: latest

- name: Install gitlab | Download settings repository file
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /home/{{ ansible_user }}
    mode: '0777'

- name: Install gitlab | Add gitlab repositiry
  become: true
  ansible.builtin.command: ./script.deb.sh

- name: Install gitlab | Install Gitlab
  become: true
  ansible.builtin.apt:
    name:
      - gitlab-ce
    state: latest

- name: Install gitlab | Copy gitlab.rb
  become: true
  ansible.builtin.template:
    src: templates/gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb

- name: Install gitlab | Reconfigure
  become: true
  ansible.builtin.command: gitlab-ctl reconfigure