---
# Tasks for create hostnames in hosts

- name: Hosts file | Add data about gitlab
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ gitlab_ip }} {{ gitlab }}.reserdukov.ru"
    create: yes

- name: Hosts file | Add data about runner
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ runner_ip }} {{ runner }}.reserdukov.ru"
    create: yes