---
# Tasks file for gitlab-ci

#- name: Add hostnames in hosts
#  include_tasks: hosts.yml

- name: Install Docker
  include_tasks: install-docker.yml
  when: ansible_nodename == {{ runner }}

- name: Genetate token_ce
  include_tasks: generate-token-ce.yml

- name: Install {{ gitlab }} | Configure and start
  include_tasks: gitlab.yml
  when: ansible_nodename == {{ gitlab }}

- name: Install {{ runner }} | Configure and start
  include_tasks: runner.yml
  when: ansible_nodename == {{ runner }}
